---
abstract: "Interact with eNom, Inc.'s reseller API"
author:
  - 'Simon Cozens <simon@cpan.org>'
  - 'Richard Simões <rsimoes@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Moose: 0
  Test::More: 0
  Test::Most: 0.22
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-eNom
no_index:
  namespace:
    - Net::eNom::Role::Commands
recommends:
  Term::ReadLine::Gnu: 0
requires:
  Any::Moose: 0
  Carp: 0
  Data::Validate::Domain: 0
  English: 0
  LWP::Simple: 0
  ParseUtil::Domain: 0
  URI: 0
  XML::Simple: 0
  perl: v5.8.5
  strict: 0
  utf8: 0
  warnings: 0
resources:
  repository: git://github.com/rsimoes/Net-eNom.git
version: v0.3.0
